WebApp/WebApp/Models/OdaKontenjan.cs
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class OdaKontenjan
{
    public int Id { get; set; }

    public int? OdalarId { get; set; }

    public int? Miktar { get; set; }

    public DateTime? BaslangicTarihi { get; set; }

    public DateTime? BitisTarihi { get; set; }

    public int? Durumu { get; set; }

    public DateTime? EklenmeTarihi { get; set; }

    public DateTime? GuncellenmeTarihi { get; set; }
    public virtual Odalar Odalar { get; set; }
}

WebApp/WebApp/Controllers/OdaKontenjanController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Controllers
{
    public class OdaKontenjanController : Controller
    {
        public IActionResult Index()
        {
            BalsenContext context = new BalsenContext();
            List<OdaKontenjan> OdaKontenjanListesi = context.OdaKontenjans.Include(x => x.Odalar).ToList();
            List<Odalar> OdalarListesi = context.Odalars.ToList();
            ViewBag.Odalar = OdalarListesi;

            return View(OdaKontenjanListesi);
        }


        [HttpPost]
        public IActionResult Ekle(OdaKontenjan odaKontenjan)
        {
            odaKontenjan.EklenmeTarihi = DateTime.Now;
            odaKontenjan.Durumu = 1;
            odaKontenjan.GuncellenmeTarihi = DateTime.Now;
            BalsenContext context = new BalsenContext();
            if (context.OdaKontenjans.Any(k => k.OdalarId == odaKontenjan.OdalarId))
            {
                ViewBag.ErrorMessage = "Bu Odaya Ait Bir Kontenjan Zaten Var.";
                List<OdaKontenjan> odakontenjanListesi = context.OdaKontenjans.Include(x => x.Odalar).ToList();
                ViewBag.Odalar = context.Odalars.ToList();
                return View("Index", odakontenjanListesi);
            }
          
            if (odaKontenjan.Miktar == null)
            {
                ViewBag.ErrorMessage = "Kontenjan Miktarı Boş Bırakılamaz.";
                List<OdaKontenjan> odakontenjanListesi = context.OdaKontenjans.Include(x => x.Odalar).ToList();
                ViewBag.Odalar = context.Odalars.ToList();
                return View("Index", odakontenjanListesi);
            }
            if (odaKontenjan.BaslangicTarihi == null)
            {
                ViewBag.ErrorMessage = "Başlangıç Tarihi Boş Bırakılamaz.";
                List<OdaKontenjan> odakontenjanListesi = context.OdaKontenjans.Include(x => x.Odalar).ToList();
                ViewBag.Odalar = context.Odalars.ToList();
                return View("Index", odakontenjanListesi);
            }
            if (odaKontenjan.BitisTarihi == null)
            {
                ViewBag.ErrorMessage = "Bitiş Tarihi Boş Bırakılamaz.";
                List<OdaKontenjan> odakontenjanListesi = context.OdaKontenjans.Include(x => x.Odalar).ToList();
                ViewBag.Odalar = context.Odalars.ToList();
                return View("Index", odakontenjanListesi);
            }
            if (odaKontenjan.BaslangicTarihi == odaKontenjan.BitisTarihi)
            {
                ViewBag.ErrorMessage = "Başlangıç Tarihi İle Bitiş Tarihi Aynı Olamaz.";
                List<OdaKontenjan> odakontenjanListesi = context.OdaKontenjans.Include(x => x.Odalar).ToList();
                ViewBag.Odalar = context.Odalars.ToList();
                return View("Index", odakontenjanListesi);
            }

            context.OdaKontenjans.Add(odaKontenjan);
                context.SaveChanges();

                return RedirectToAction("Index");
            }

           
        
        [HttpPost]
        public IActionResult Sil(int id)
        {
            BalsenContext dbContext = new BalsenContext();
            var odaKontenjan = dbContext.OdaKontenjans.Find(id);
            if (odaKontenjan != null)
            {
                dbContext.Remove(odaKontenjan);
                dbContext.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Update(int id)
        {
            BalsenContext context = new BalsenContext();
            List<Odalar> OdalarListesi = context.Odalars.ToList();
            ViewBag.Odalar = OdalarListesi;
            OdaKontenjan kontenjan = context.OdaKontenjans.Where(k => k.Id == id).FirstOrDefault();
            if (kontenjan == null)
            {
                return RedirectToAction("Index");
            }

            return View("Update", kontenjan);
        }

        [HttpPost]
        public IActionResult DoUpdate(OdaKontenjan kontenjan)
        {
            kontenjan.GuncellenmeTarihi = DateTime.Now;
            BalsenContext context = new BalsenContext();
            if (context.OdaKontenjans.Any(k => k.OdalarId == kontenjan.OdalarId && k.Id!=kontenjan.Id))
            {
                ViewBag.ErrorMessage = "Bu Odaya Ait Bir Kontenjan Zaten Var.";
                List<OdaKontenjan> odakontenjanListesi = context.OdaKontenjans.Include(x => x.Odalar).ToList();
                ViewBag.Odalar = context.Odalars.ToList();
                return View("Index", odakontenjanListesi);
            }
           
            if (kontenjan.Miktar == null)
            {
                ViewBag.ErrorMessage = "Kontenjan Miktarı Boş Bırakılamaz.";
                List<OdaKontenjan> odakontenjanListesi = context.OdaKontenjans.Include(x => x.Odalar).ToList();
                ViewBag.Odalar = context.Odalars.ToList();
                return View("Index", odakontenjanListesi);
            }
            context.Update(kontenjan);
                context.SaveChanges();
                return RedirectToAction("Index");
            

           
        }

    }
}

WebApp/WebApp/Views/OdaKontenjan/Index.cshtml
@using WebApp.Models;
@model List<WebApp.Models.OdaKontenjan>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutWebAdmin.cshtml";
}
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-6">
                <section class="panel">
                    <header class="panel-heading">
                        Oda Kontenjan (@Model.Count() Adet Kayıt Bulunmaktadır)
                    </header>
                    <div class="panel-body">
                        <form method="post" action="@Url.Action("Ekle", "OdaKontenjan")">
                            <div class="row">
                                <div class="form-group col-md-5">
                                    <label for="OdaId">Oda</label>
                                    <select class="form-control" id="OdalarId" name="OdalarId" >
                                    @foreach (var odalar in ViewBag.Odalar)
                                    {
                                            <option value="@odalar.Id">@odalar.Adi</option>
                                    }
                                    </select>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="Miktar">Miktar</label>
                                    <input type="number" class="form-control" id="Miktar" name="Miktar" onkeypress="return event.charCode >= 48 && event.charCode <= 57" min="0" max="10">
                                </div>
                            </div>

                            <div class="row">

                                <div class="form-group col-md-4">
                                    <label for="BaslangicTarihi">Başlangıç Tarihi</label>
                                    <input type="datetime-local" class="form-control" id="BaslangicTarihi" name="BaslangicTarihi">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="BitisTarihi">Bitiş Tarihi</label>
                                    <input type="datetime-local" class="form-control" id="BitisTarihi" name="BitisTarihi">
                                </div>


                            </div>
                            <button type="submit" class="btn btn-info">Ekle</button>
                        </form>
                        @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
                        {
                            <div style="margin-top:10px;" class="alert alert-block alert-danger fade in">
                                <button data-dismiss="alert" class="close close-sm" type="button">
                                    <i class="icon-remove"></i>
                                </button>
                                <strong>Hata!</strong> @ViewBag.ErrorMessage
                            </div>
                        }


                    </div>
                </section>
            </div>
        </div>
        <section class="panel">
            <table class="table table-striped">
                <thead>
                    <tr>

                        <th>Oda</th>
                        <th>Miktar</th>


                        <th>Başlangıç Tarihi</th>
                        <th>Bitiş Tarihi</th>

                    </tr>
                </thead>
                <tbody>
                                    @foreach (var odaKontenjan in Model)
                                    {
                        <tr>

                            <td>@odaKontenjan.Odalar.Adi</td>
                            <td>@odaKontenjan.Miktar</td>


                            <td>@odaKontenjan.BaslangicTarihi</td>
                            <td>@odaKontenjan.BitisTarihi</td>

                            <td>
                                <form method="post" action="@Url.Action("Update", "OdaKontenjan")" style="display: inline;">
                                    <input type="hidden" name="id" value="@odaKontenjan.Id" />
                                    <button type="submit" class="btn btn-primary btn-xs"><i class="icon-pencil"></i></button>
                                </form>
                                <form method="post" action="@Url.Action("Sil", "OdaKontenjan")" style="display: inline;">
                                    <input type="hidden" name="id" value="@odaKontenjan.Id" />
                                    <button type="submit" class="btn btn-danger btn-xs" onclick="confirmSilme(event)"><i class="icon-trash"></i></button>
                                </form>
                            </td>

                        </tr>
                                    }
                </tbody>
            </table>
        </section>
    </section>
</section>

WebApp/WebApp/Views/OdaKontenjan/Update.cshtml
@using WebApp.Models;
@model OdaKontenjan;


@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutWebAdmin.cshtml";
}
<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-6">
                <section class="panel">
                    <header class="panel-heading">
                        Oda Kontenjan Güncelle
                    </header>
                    <div class="panel-body">
                        <form method="post" action="@Url.Action("DoUpdate", "OdaKontenjan")">
                            <div class="row">
                                <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">
                                <div class="form-group col-md-5">
                                    <label for="Adi">Oda</label>
                                    <select name="OdalarId" class="form-control" id="OdalarId">
                                        @foreach (var oda in ViewBag.Odalar)
                                        {
                                            <option value="@oda.Id" @(oda.Id == Model.OdalarId ? "selected" : "")>@oda.Adi</option>
                                        }
                                    </select>

                                   
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="Miktar">Miktar</label>
                                    <input type="number" class="form-control" id="Miktar" name="Miktar" value="@Model.Miktar" onkeypress="return event.charCode >= 48 && event.charCode <= 57" min="0" max="10">
                                </div>
                            </div>

                            <div class="row">

                                <div class="form-group col-md-4">
                                    <label for="BaslangicTarihi">Başlangıç Tarihi</label>
                                    <input type="text" class="form-control" id="BaslangicTarihi" name="BaslangicTarihi" value="@Model.BaslangicTarihi">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="BitisTarihi">Bitiş Tarihi</label>
                                    <input type="text" class="form-control" id="BitisTarihi" name="BitisTarihi" value="@Model.BitisTarihi">
                                </div>


                            </div>
                            <input type="hidden" class="form-control" id="Durumu" name="Durumu" value="@Model.Durumu">
                            <input type="hidden" class="form-control" id="EklenmeTarihi" name="EklenmeTarihi" value="@Model.EklenmeTarihi">
                            <input type="hidden" class="form-control" id="GuncellenmeTarihi" name="GuncellenmeTarihi" value="@Model.GuncellenmeTarihi">
                            <button type="submit" class="btn btn-info">Güncelle</button>
                        </form>
                        @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
                        {
                            <div style="margin-top:10px;" class="alert alert-block alert-danger fade in">
                                <button data-dismiss="alert" class="close close-sm" type="button">
                                    <i class="icon-remove"></i>
                                </button>
                                <strong>Hata!</strong> @ViewBag.ErrorMessage
                            </div>
                        }


                    </div>
                </section>
            </div>
        </div>
    </section>
</section>