WebApp/WebApp/Controllers/MusteriController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Controllers
{
    public class MusteriController : Controller
    {
        public IActionResult Index()
        {
            BalsenContext context = new BalsenContext();
            List<Musteri> MusteriListesi = context.Musteris.ToList();

            return View(MusteriListesi);
        }


        [HttpPost]
        public IActionResult Ekle(Musteri musteri)
        {
            if (ModelState.IsValid)
            {
                musteri.EklenmeTarihi = DateTime.Now;
                musteri.Durumu = 1;
                musteri.GuncellenmeTarihi = DateTime.Now;
                musteri.KaraListe = 0;
                musteri.KaraListeAciklama = "Girilmedi";
                musteri.MusteriTuru = "Girilmedi";
                BalsenContext context = new BalsenContext();
                if (context.Musteris.Any(k => k.AdiSoyadi == musteri.AdiSoyadi && k.Telefon == musteri.Telefon))
                {
                    ViewBag.ErrorMessage = "Bu Müşteri Zaten Kayıtlı.";
                    List<Musteri> musteriListesi = context.Musteris.ToList();
                    return View("Index", musteriListesi);
                }
                if (context.Musteris.Any(k => k.TcNo == musteri.TcNo ))
                {
                    ViewBag.ErrorMessage = "Bu TC Kimlik Numarası Zaten Kullanılıyor.";
                    List<Musteri> musteriListesi = context.Musteris.ToList();
                    return View("Index", musteriListesi);
                }
                if (context.Musteris.Any(k => k.Email == musteri.Email))
                {
                    ViewBag.ErrorMessage = "Bu E-posta Zaten Kullanılıyor.";
                    List<Musteri> musteriListesi = context.Musteris.ToList();
                    return View("Index", musteriListesi);
                }
                if (musteri.Email==null)
                {
                    ViewBag.ErrorMessage = "E-posta Boş Bırakılamaz.";
                    List<Musteri> musteriListesi = context.Musteris.ToList();
                    return View("Index", musteriListesi);
                }
                if (musteri.AdiSoyadi == null)
                {
                    ViewBag.ErrorMessage = "Müşteri Adı Soyadı Boş Bırakılamaz.";
                    List<Musteri> musteriListesi = context.Musteris.ToList();
                    return View("Index", musteriListesi);
                }
                if (musteri.Telefon == null)
                {
                    ViewBag.ErrorMessage = "Telefon Numarası Boş Bırakılamaz.";
                    List<Musteri> musteriListesi = context.Musteris.ToList();
                    return View("Index", musteriListesi);
                }
                context.Musteris.Add(musteri);
                context.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }
        [HttpPost]
        public IActionResult Sil(int id)
        {
            BalsenContext dbContext = new BalsenContext();

            var musteri = dbContext.Musteris.Find(id);
            var rezervasyon = dbContext.OtelRezervasyons.FirstOrDefault(r => r.MusteriId == id);

            if (musteri != null)
            {
                if (rezervasyon != null)
                {
                    ViewBag.ErrorMessage = "Önce Bu Müşteriye Ait Rezervasyon Kaydını Silmelisiniz.";
                    List<Musteri> musteriListesi = dbContext.Musteris.ToList();
                    return View("Index", musteriListesi);
                }

                dbContext.Remove(musteri);
                dbContext.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Update(int id)
        {
            BalsenContext context = new BalsenContext();
            Musteri musteri = context.Musteris.Where(k => k.Id == id).FirstOrDefault();
            if (musteri == null)
            {
                return RedirectToAction("Index");
            }

            return View("Update", musteri);
        }

        [HttpPost]
        public IActionResult DoUpdate(Musteri musteri)
        {
            if (ModelState.IsValid)
            {
                musteri.GuncellenmeTarihi = DateTime.Now;
                BalsenContext context = new BalsenContext();
                if (context.Musteris.Any(k => k.AdiSoyadi == musteri.AdiSoyadi && k.Telefon == musteri.Telefon && k.Id != musteri.Id))
                {
                    ViewBag.ErrorMessage = "Bu Müşteri Zaten Kayıtlı.";
                    List<Musteri> musteriListesi = context.Musteris.ToList();
                    return View("Index", musteriListesi);
                }
                if (context.Musteris.Any(k => k.TcNo == musteri.TcNo && k.Id != musteri.Id))
                {
                    ViewBag.ErrorMessage = "Bu TC Kimlik Numarası Zaten Kullanılıyor.";
                    List<Musteri> musteriListesi = context.Musteris.ToList();
                    return View("Index", musteriListesi);
                }
                if (context.Musteris.Any(k => k.Email == musteri.Email && k.Id != musteri.Id))
                {
                    ViewBag.ErrorMessage = "Bu E-posta Zaten Kullanılıyor.";
                    List<Musteri> musteriListesi = context.Musteris.ToList();
                    return View("Index", musteriListesi);
                }
                if (musteri.Email == null)
                {
                    ViewBag.ErrorMessage = "E-posta Boş Bırakılamaz.";
                    List<Musteri> musteriListesi = context.Musteris.ToList();
                    return View("Index", musteriListesi);
                }
                if (musteri.AdiSoyadi == null)
                {
                    ViewBag.ErrorMessage = "Müşteri Adı Soyadı Boş Bırakılamaz.";
                    List<Musteri> musteriListesi = context.Musteris.ToList();
                    return View("Index", musteriListesi);
                }
                if (musteri.Telefon == null)
                {
                    ViewBag.ErrorMessage = "Telefon Numarası Boş Bırakılamaz.";
                    List<Musteri> musteriListesi = context.Musteris.ToList();
                    return View("Index", musteriListesi);
                }
                context.Update(musteri);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View("Update", musteri);
        }

    }
}

WebApp/WebApp/Views/Deneme/Index.cshtml
@using WebApp.Models;
@model List<WebApp.Models.Musteri>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutWebAdmin.cshtml";
}
      <section id="main-content">
          <section class="wrapper">
              <!-- page start-->
              <div class="row">
                  <div class="col-lg-12">
                      <section class="panel">
                          <header class="panel-heading">
                        Müşteri (@Model.Count() Adet Kayıt Bulunmaktadır)
                          </header>
                          <div class="panel-body">
                                <div class="adv-table">
                                    <table  class="display table table-bordered table-striped" id="example">
                                <thead>
                                    <tr>

                                        <th>Adı Soyadı</th>
                                        <th>TC No</th>
                                        <th>Telefon</th>
                                        <th>Açıklama</th>
                                        <th>E-mail</th>
                                        <th>İşlemler</th>



                                    </tr>
                                </thead>
                                      <tbody>
                                      @foreach (var musteri in Model)
                    {
                                      <tr class="gradeA">
                                            <td>@musteri.AdiSoyadi</td>
                                            <td>@musteri.TcNo</td>
                                            <td>@musteri.Telefon</td>
                                            <td>@musteri.Aciklama</td>
                                            <td>@musteri.Email</td>
                                            <td>
                                                <form method="post" action="@Url.Action("Update", "Musteri")" style="display: inline;">
                                                    <input type="hidden" name="id" value="@musteri.Id" />
                                                    <button type="submit" class="btn btn-primary btn-xs"><i class="icon-pencil"></i></button>
                                                </form>
                                                <form method="post" action="@Url.Action("Sil", "Musteri")" style="display: inline;">
                                                    <input type="hidden" name="id" value="@musteri.Id" />
                                                    <button type="submit" class="btn btn-danger btn-xs" onclick="confirmSilme(event)"><i class="icon-trash"></i></button>
                                                </form>
                                            </td>

                                      </tr>
                    }
                           
                              
                                
                                      </tbody>
                                     
                          </table>
                                </div>
                          </div>
                      </section>
                  </div>
              </div>
              <!-- page end-->
          </section>
      </section>