WebApp/WebApp/Models/OtelRezervasyon.cs
using System;
using System.Collections.Generic;

namespace WebApp.Models;

public partial class OtelRezervasyon
{
    public int Id { get; set; }

    public DateTime? GirisTarihi { get; set; }

    public DateTime? CikisTarihi { get; set; }

    public short? Yetiskin { get; set; }

    public short? UcretliCocuk { get; set; }

    public short? CocukSayisi { get; set; }

    public short? CocukYasi1 { get; set; }

    public short? CocukYasi2 { get; set; }
    public short? CocukYasi3 { get; set; }

    public short? CocukYasi4{ get; set; }


    public int OdalarId { get; set; }

    public decimal GecelikUcret { get; set; }

    public string? ParaBirimi { get; set; }

    public short? Durumu { get; set; }

    public DateTime? GuncellenmeTarihi { get; set; }

    public string? MusteriTuru { get; set; }

    public int MusteriId { get; set; }

    public DateTime? EklenmeTarihi { get; set; }

    public int? Onay { get; set; }

    public int? FiyatId { get; set; }

    public decimal ToplamUcret { get; set; }

    public int? KonaklamaGunSayisi { get; set; }

    //public virtual Fiyat Fiyat { get; set; }

    public virtual Musteri Musteri { get; set; }

    public virtual Odalar Odalar { get; set; }
}

WebApp/WebApp/Controllers/OtelRezervasyonController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace WebApp.Controllers
{
    public class OtelRezervasyonController : Controller
    {
        public IActionResult Index()
        {
            BalsenContext context = new BalsenContext();
            List<OtelRezervasyon> OtelRezervasyonListesi = context.OtelRezervasyons.Include(x => x.Musteri).Include(x => x.Odalar).ToList();
            List<Musteri> MusteriListesi = context.Musteris.ToList();
            ViewBag.Musteri = MusteriListesi;
            List<Fiyat> FiyatListesi = context.Fiyats.ToList();
            ViewBag.Fiyat = FiyatListesi;
            List<Odalar> OdalarListesi = context.Odalars.ToList();
            ViewBag.Odalar = OdalarListesi;
            return View(OtelRezervasyonListesi);
        }


        [HttpPost]
        public IActionResult Ekle(OtelRezervasyon rezerve, decimal odafiyat, int toplamkisi)
        {
            using (BalsenContext context = new BalsenContext())
            {
                Fiyat fiyat = context.Fiyats.FirstOrDefault(f => f.OdalarId == rezerve.OdalarId);
                if (fiyat == null)
                {
                   
                    ViewBag.ErrorMessage = "Bu Odaya Ait Fiyat Verisi Bulunamadı.";
                    List<OtelRezervasyon> OtelRezervasyonListesi = context.OtelRezervasyons.Include(x => x.Musteri).Include(x => x.Odalar).ToList();
                    ViewBag.Musteri = context.Musteris.ToList();
                    ViewBag.Fiyat = context.Fiyats.ToList();
                    ViewBag.Odalar = context.Odalars.ToList();
                    return View("Index", OtelRezervasyonListesi);

                }
                FiyatCarpan carpan = context.FiyatCarpans.FirstOrDefault(c => c.OdalarId == rezerve.OdalarId);

                if (carpan == null)
                {
                    ViewBag.ErrorMessage = "Bu Odaya Ait Fiyat Çarpanı Verisi Bulunamadı.";
                    List<OtelRezervasyon> OtelRezervasyonListesi = context.OtelRezervasyons.Include(x => x.Musteri).Include(x => x.Odalar).ToList();
                    ViewBag.Musteri = context.Musteris.ToList();
                    ViewBag.Fiyat = context.Fiyats.ToList();
                    ViewBag.Odalar = context.Odalars.ToList();
                    return View("Index", OtelRezervasyonListesi);

                }


                rezerve.EklenmeTarihi = DateTime.Now;
            rezerve.Durumu = 1;
            rezerve.GuncellenmeTarihi = DateTime.Now;
            //rezerve.Cocuk_2 = 0;
            //rezerve.Cocuk_3 = 0;
            rezerve.ParaBirimi = "TL";
            rezerve.MusteriTuru = "Belirtilmedi";
            rezerve.Onay = 0;
           
                if(context.OtelRezervasyons.Any(r => r.OdalarId == rezerve.OdalarId))
                {
                    ViewBag.ErrorMessage = "Bu Odaya Ait Bir Rezervasyon Zaten Var.";
                    List<OtelRezervasyon> OtelRezervasyonListesi = context.OtelRezervasyons.Include(x => x.Musteri).Include(x => x.Odalar).ToList();
                    ViewBag.Musteri=context.Musteris.ToList();
                    ViewBag.Fiyat= context.Fiyats.ToList();
                    ViewBag.Odalar= context.Odalars.ToList();
                    return View("Index", OtelRezervasyonListesi);
                }
                if (context.OtelRezervasyons.Any(r => r.MusteriId == rezerve.MusteriId))
                {
                    ViewBag.ErrorMessage = "Bu Müşteriye Ait Bir Rezervasyon Zaten Var.";
                    List<OtelRezervasyon> OtelRezervasyonListesi = context.OtelRezervasyons.Include(x => x.Musteri).Include(x => x.Odalar).ToList();
                    ViewBag.Musteri = context.Musteris.ToList();
                    ViewBag.Fiyat = context.Fiyats.ToList();
                    ViewBag.Odalar = context.Odalars.ToList();
                    return View("Index", OtelRezervasyonListesi);
                }
                if (rezerve.GirisTarihi==null)
                {
                    ViewBag.ErrorMessage = "Giriş Tarihi Boş Bırakılamaz.";
                    List<OtelRezervasyon> OtelRezervasyonListesi = context.OtelRezervasyons.Include(x => x.Musteri).Include(x => x.Odalar).ToList();
                    ViewBag.Musteri = context.Musteris.ToList();
                    ViewBag.Fiyat = context.Fiyats.ToList();
                    ViewBag.Odalar = context.Odalars.ToList();
                    return View("Index", OtelRezervasyonListesi);
                }
                if (rezerve.CikisTarihi == null)
                {
                    ViewBag.ErrorMessage = "Çıkış Tarihi Boş Bırakılamaz.";
                    List<OtelRezervasyon> OtelRezervasyonListesi = context.OtelRezervasyons.Include(x => x.Musteri).Include(x => x.Odalar).ToList();
                    ViewBag.Musteri = context.Musteris.ToList();
                    ViewBag.Fiyat = context.Fiyats.ToList();
                    ViewBag.Odalar = context.Odalars.ToList();
                    return View("Index", OtelRezervasyonListesi);
                }
                if (rezerve.GirisTarihi==rezerve.CikisTarihi)
                {
                    ViewBag.ErrorMessage = "Giriş Tarihi İle Çıkış Tarihi Aynı Olamaz.";
                    List<OtelRezervasyon> OtelRezervasyonListesi = context.OtelRezervasyons.Include(x => x.Musteri).Include(x => x.Odalar).ToList();
                    ViewBag.Musteri = context.Musteris.ToList();
                    ViewBag.Fiyat = context.Fiyats.ToList();
                    ViewBag.Odalar = context.Odalars.ToList();
                    return View("Index", OtelRezervasyonListesi);
                }
                TimeSpan GunHesaplama = rezerve.CikisTarihi.Value - rezerve.GirisTarihi.Value;
                int GunSayisi = GunHesaplama.Days;
                rezerve.KonaklamaGunSayisi = GunSayisi;
                if (GunSayisi < 1)
                {
                    ViewBag.ErrorMessage = "İki Tarih Arasında En Az 1 Gün Fark Olmalıdır.";
                    List<OtelRezervasyon> OtelRezervasyonListesi = context.OtelRezervasyons.Include(x => x.Musteri).Include(x => x.Odalar).ToList();
                    ViewBag.Musteri = context.Musteris.ToList();
                    ViewBag.Fiyat = context.Fiyats.ToList();
                    ViewBag.Odalar = context.Odalars.ToList();
                    return View("Index", OtelRezervasyonListesi);
                }
                if (rezerve.Yetiskin == null)
                {
                    ViewBag.ErrorMessage = "Yetişkin Sayısı Boş Bırakılamaz.";
                    List<OtelRezervasyon> OtelRezervasyonListesi = context.OtelRezervasyons.Include(x => x.Musteri).Include(x => x.Odalar).ToList();
                    ViewBag.Musteri = context.Musteris.ToList();
                    ViewBag.Fiyat = context.Fiyats.ToList();
                    ViewBag.Odalar = context.Odalars.ToList();
                    return View("Index", OtelRezervasyonListesi);
                }
                if (rezerve.CocukSayisi == null)
                {
                    ViewBag.ErrorMessage = "Çocuk Sayısı Boş Bırakılamaz.";
                    List<OtelRezervasyon> OtelRezervasyonListesi = context.OtelRezervasyons.Include(x => x.Musteri).Include(x => x.Odalar).ToList();
                    ViewBag.Musteri = context.Musteris.ToList();
                    ViewBag.Fiyat = context.Fiyats.ToList();
                    ViewBag.Odalar = context.Odalars.ToList();
                    return View("Index", OtelRezervasyonListesi);
                }
                if (rezerve.UcretliCocuk == null)
                {
                    ViewBag.ErrorMessage = "Ücretli Çocuk Sayısı Boş Bırakılamaz.";
                    List<OtelRezervasyon> OtelRezervasyonListesi = context.OtelRezervasyons.Include(x => x.Musteri).Include(x => x.Odalar).ToList();
                    ViewBag.Musteri = context.Musteris.ToList();
                    ViewBag.Fiyat = context.Fiyats.ToList();
                    ViewBag.Odalar = context.Odalars.ToList();
                    return View("Index", OtelRezervasyonListesi);
                }
               

               
                if (fiyat != null && carpan != null)
                {
                    odafiyat = (decimal)fiyat.Tutar;
                    toplamkisi = rezerve.Yetiskin.Value + rezerve.CocukSayisi.Value + rezerve.UcretliCocuk.Value;
                    if (toplamkisi == 1)
                    {
                        decimal tekKisiFiyati = carpan.TekKisilik.Value * odafiyat;
                        rezerve.GecelikUcret = tekKisiFiyati;
                        rezerve.ToplamUcret = rezerve.GecelikUcret * GunSayisi;




                    }
                    if (toplamkisi == 2)
                    {
                        decimal ciftKisiFiyati = carpan.CiftKisilik.Value * odafiyat;
                        rezerve.GecelikUcret = ciftKisiFiyati;
                        rezerve.ToplamUcret = rezerve.GecelikUcret * GunSayisi;




                    }
                    if (toplamkisi == 3)
                    {
                        decimal UcKisiFiyati = carpan.UcKisilik.Value * odafiyat;
                        rezerve.GecelikUcret = UcKisiFiyati;
                        rezerve.ToplamUcret = rezerve.GecelikUcret * GunSayisi;




                    }
                    if (toplamkisi == 4)
                    {
                        decimal dortKisiFiyati = carpan.DortKisilik.Value * odafiyat;
                        rezerve.GecelikUcret = dortKisiFiyati;
                        rezerve.ToplamUcret = rezerve.GecelikUcret * GunSayisi;




                    }
                    if (toplamkisi == 5)
                    {
                        decimal besKisiFiyati = carpan.BesKisilik.Value * odafiyat;
                        rezerve.GecelikUcret = besKisiFiyati;
                        rezerve.ToplamUcret = rezerve.GecelikUcret * GunSayisi;

WebApp/WebApp/Views/OtelRezervasyon/Update.cshtml
@using WebApp.Models;
@model OtelRezervasyon

@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_LayoutWebAdmin.cshtml";
}




<section id="main-content">
    <section class="wrapper">
        <div class="row">
            <div class="col-lg-8">
                <section class="panel">
                    <header class="panel-heading">
                        Otel Rezervasyon Güncelle
                    </header>
                    <div class="panel-body">
                        <form method="post" action="@Url.Action("DoUpdate", "OtelRezervasyon")">
                            <div class="row">

                            
                                <div class="form-group col-md-4">
                                    <label for="Adi">Oda</label>
                                    <select name="OdalarId" class="form-control" id="OdalarId">
                                        @foreach (var oda in ViewBag.Odalar)
                                        {
                                            <option value="@oda.Id" @(oda.Id == Model.OdalarId ? "selected" : "")>@oda.Adi</option>
                                        }
                                    </select>
                                </div>

                                <div class="form-group col-md-4">
                                    <label for="Adi">Müşteri</label>
                                    <select name="MusteriId" class="form-control" id="MusteriId">
                                        @foreach (var musteri in ViewBag.Musteri)
                                        {
                                            <option value="@musteri.Id" @(musteri.Id == Model.MusteriId ? "selected" : "")>@musteri.AdiSoyadi</option>
                                        }
                                    </select>
                                </div>

                            </div>

                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label for="GirisTarihi">Giriş Tarihi</label>
                                    <input type="text" class="form-control" id="GirisTarihi" name="GirisTarihi" value="@Model.GirisTarihi">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="CikisTarihi">Çıkış Tarihi</label>
                                    <input type="text" class="form-control" id="CikisTarihi" name="CikisTarihi" value="@Model.CikisTarihi">
                                </div>
                            </div>

                            <div class="row">
                                <div class="form-group col-md-2">
                                    <label for="Yetiskin">Yetişkin</label>
                                    <input type="number" class="form-control" min="0" id="Yetiskin" name="Yetiskin" value="@Model.Yetiskin">
                                </div>

                            <div id="spinner4">
                                <div class="form-group col-md-4">
                                    <label for="CocukSayisi">Çocuk</label>
                                    <div class="input-group" style="width:120px;">
                                        <div class="spinner-buttons input-group-btn">
                                            <button id="AzaltBtn" type="button" class="btn spinner-down btn-danger">
                                                <i class="icon-minus"></i>
                                            </button>
                                        </div>
                                        <input id="CocukSayisi" name="CocukSayisi" type="text" class="spinner-input CocukSayisiInput form-control" maxlength="3" min="0" max="4" value="@Model.CocukSayisi">
                                        <div class="spinner-buttons input-group-btn">
                                            <button id="CogaltBtn" type="button" class="btn spinner-up btn-warning">
                                                <i class="icon-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-3 CocukYas1">
                                    <label for="CocukYasi1">Çocuk 1 Yaş</label>
                                    <input name="CocukYasi1" class="form-control" id="CocukYasi1" type="number" min="0" max="17" value="@Model.CocukYasi1" data-prev-value="0" />
                                </div>
                                <div class="form-group col-md-3 CocukYas2">
                                    <label for="CocukYasi2">Çocuk 2 Yaş</label>
                                    <input name="CocukYasi2" class="form-control" id="CocukYasi2" type="number" min="0" max="17" value="@Model.CocukYasi2" data-prev-value="0" />
                                </div>
                                <div class="form-group col-md-3 CocukYas3">
                                    <label for="CocukYasi3">Çocuk 3 Yaş</label>
                                    <input name="CocukYasi3" class="form-control" id="CocukYasi3" type="number" min="0" max="17" value="@Model.CocukYasi3" data-prev-value="0" />
                                </div>
                                <div class="form-group col-md-3 CocukYas4">
                                    <label for="CocukYasi4">Çocuk 4 Yaş</label>
                                    <input name="CocukYasi4" class="form-control" id="CocukYasi4" type="number" min="0" max="17" value="@Model.CocukYasi4" data-prev-value="0" />
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-md-4">
                                 @*   <label for="UcretliCocuk">Ücretli Çocuk</label>*@
                                    <input type="hidden" class="form-control" min="0" id="UcretliCocuk" name="UcretliCocuk" value="@Model.UcretliCocuk" readonly>
                                </div>
                               
                           
                            <input type="hidden" class="form-control" id="Durumu" name="Durumu" value="@Model.Durumu">
                            <input type="hidden" class="form-control" id="EklenmeTarihi" name="EklenmeTarihi" value="@Model.EklenmeTarihi">
                            <input type="hidden" class="form-control" id="GuncellenmeTarihi" name="GuncellenmeTarihi" value="@Model.GuncellenmeTarihi">
                            
                            
                            <input type="hidden" class="form-control" id="KapasiteHarici" name="KapasiteHarici" value="@Model.Onay">
                            <input type="hidden" class="form-control" id="KapasiteHarici" name="KapasiteHarici" value="@Model.MusteriTuru">
                            <input type="hidden" class="form-control" id="KapasiteHarici" name="KapasiteHarici" value="@Model.ParaBirimi">



                            </div>
                            <div class="row">
                                <div class="form-group col-md-4">
                                    <label class="label_check" for="YasDogrulama">
                                        <input name="YasDogrulama" id="YasDogrulama" value="1" type="checkbox" /> Çocuk Yaş Bilgilerimi Doğru Girdim.
                                    </label>
                                </div>
                            </div>
                            <div class="row">
                            <div class="form-group col-md-10">
                                <button type="submit" class="btn btn-info">Güncelle</button>
                            </div>
                            </div>
                            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">

                        </form>
                       


                    </div>
                </section>
            </div>
            <div class="col-lg-5">
                @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
                {
                    <div style="margin-top:10px;" class="alert alert-block alert-danger fade in">
                        <button data-dismiss="alert" class="close close-sm" type="button">
                            <i class="icon-remove"></i>
                        </button>
                        <strong>Hata!</strong> @ViewBag.ErrorMessage
                    </div>
                }
            </div>
        </div>
    </section>
</section>


<script src="/WebAdminTheme/js/jquery-1.8.3.min.js"></script>

<script>
    $(document).ready(function () {
       var DoluCocukInput= parseInt($("input[name^='CocukYasi']").val());
        var DoluCocukPrevValue = $("input[name^='CocukYasi']").data("prev-value");
        var CocukSayisiDegeri = parseInt($(".CocukSayisiInput").val());
        var CocukInputlari = $("#CocukYasi1, #CocukYasi2, #CocukYasi3, #CocukYasi4,  #CocukSayisi");

        $("button[type='submit']").prop("disabled", true);
        $("#YasDogrulama").change(function () {
            if ($(this).is(":checked")) {
                $("button[type='submit']").prop("disabled", false);
                $("#AzaltBtn").hide();
                $("#CogaltBtn").hide()
                CocukInputlari.prop("readonly",true);
            } else {
                $("button[type='submit']").prop("disabled", true);
                $("#AzaltBtn").show();
                $("#CogaltBtn").show();
                CocukInputlari.prop("readonly", false);
             
            }
        });

        for (var i = 1; i <= 4; i++) {
            var cocukYasiInput = $("#CocukYasi" + i);
            if (cocukYasiInput.val() === "0") {
                cocukYasiInput.closest(".CocukYas" + i).hide();
            }
        }


        $(".CocukSayisiInput").on("keydown", function (e) {
            e.preventDefault();
        });

        // ÇOĞALTMA BÖLÜMÜ

        $("#CogaltBtn").click(function () {

            if (CocukSayisiDegeri < 4) {
                CocukSayisiDegeri += 1;
                $(".CocukSayisiInput").val(CocukSayisiDegeri);

                if (CocukSayisiDegeri <= 4) {
                    $(".CocukYas" + CocukSayisiDegeri).show();

                }

                var yeniCocuk = $(".CocukYas").eq(0).clone();
                yeniCocuk.find("select").val("0");

                $(".CocukYas").after(yeniCocuk);
            }
        });
        // AZALTMA BÖLÜMÜ
        $("#AzaltBtn").click(function () {

            if (CocukSayisiDegeri > 0) {
                CocukSayisiDegeri -= 1;
                $(".CocukSayisiInput").val(CocukSayisiDegeri);

                var CocukYas = $("#CocukYasi" + (CocukSayisiDegeri + 1));

                var CocukYasDiv = $(".CocukYas" + (CocukSayisiDegeri + 1));

                var CocukYasDeger = CocukYas.val();

                CocukYasDiv.hide();

              

                CocukYas.val(0);





                $(".CocukYas:last").remove();

                
            }
        });

       



    });
</script>