WebApp/WebApp/Controllers/GirisYapController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;

namespace WebApp.Controllers
{
    public class GirisYapController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(Kullanicilar user)
        {
            if (ModelState.IsValid)
            {
                BalsenContext context = new BalsenContext();
                context.Kullanicilars.Add(user);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        

        [HttpPost]
        public IActionResult GirisKontrol(string adi, string sifre)
        {
            BalsenContext dbContext = new BalsenContext();
            var kullanici = dbContext.Kullanicilars.FirstOrDefault(k => k.Adi == adi && k.Sifre == sifre && k.Durumu == 1);

            if (kullanici != null)
            {
               
                // Kullanıcı doğrulandı, yönlendirme yap
                HttpContext.Session.SetString("KullaniciAdi", kullanici.Adi);

                dbContext.SaveChanges();
                return RedirectToAction("Index", "Kullanicilar");
            }
            else
            {
                // Kullanıcı bulunamadı veya durumu 1 değil, hata mesajı gösterebilirsiniz
                
                ViewBag.ErrorMessage = "Geçersiz kullanıcı adı veya şifre.";
                return View("Index");
            }
        }
    }
}

WebApp/WebApp/Controllers/KaydolController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class KaydolController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Ekle(Kullanicilar user)
        {
            BalsenContext context = new BalsenContext();
           
                if (ModelState.IsValid)
                {
                    if (context.Kullanicilars.Any(k => k.Adi == user.Adi))
                    {
                        ViewBag.ErrorMessage = "Bu Kullanıcı Adı Zaten Kullanılıyor";
                        return View("Index");
                    }

                    context.Kullanicilars.Add(user);
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View("Index", user);
            }

        }
    }

WebApp/WebApp/Views/GirisYap/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="img/favicon.png">

    <title>Balşen Hotel Yönetim Paneli</title>

    <!-- Bootstrap core CSS -->
    <link href="/WebAdminTheme/css/bootstrap.min.css" rel="stylesheet">
    <link href="/WebAdminTheme/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="/WebAdminTheme/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="/WebAdminTheme/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen" />
    <link rel="stylesheet" href="css/owl.carousel.css" type="text/css">
    <!-- Custom styles for this template -->
    <link href="/WebAdminTheme/css/style.css" rel="stylesheet">
    <link href="/WebAdminTheme/css/style-responsive.css" rel="stylesheet" />



</head>

<body>
    <div class="login-body">
        <div class="container">

            <form method="post" class="form-signin" action="@Url.Action("GirisKontrol", "GirisYap")">
                <h2 class="form-signin-heading">OTEL YÖNETİM</h2>
                <div class="login-wrap">
                    <input type="text" class="form-control" id="Adi" name="Adi" placeholder="Kullanıcı Adı">
                    <input type="password" class="form-control" id="Sifre" name="Sifre" placeholder="Şifre">
                    
                    <button class="btn btn-lg btn-login btn-block" type="submit">GİRİŞ</button>
                    @if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
                    {
                        <div style="margin-top:20px;" class="alert alert-block alert-danger fade in">
                            <button data-dismiss="alert" class="close close-sm" type="button">
                                <i class="icon-remove"></i>
                            </button>
                            <strong>Hata!</strong> @ViewBag.ErrorMessage
                        </div>
                    }
                    
                    <div class="registration">
                        Hesabın Yok Mu?
                        <a class="" href="@Url.Action("Index","Kaydol")">
                            Hemen Kaydol
                        </a>
                    </div>

                </div>

                

            </form>

        </div>

    </div>




    <!-- js placed at the end of the document so the pages load faster -->
    <script src="/WebAdminTheme/js/jquery.js"></script>
    <script src="/WebAdminTheme/js/jquery-1.8.3.min.js"></script>
    <script src="/WebAdminTheme/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="/WebAdminTheme/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="/WebAdminTheme/js/jquery.scrollTo.min.js"></script>
    <script src="/WebAdminTheme/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="/WebAdminTheme/js/jquery.sparkline.js" type="text/javascript"></script>
    <script src="/WebAdminTheme/assets/jquery-easy-pie-chart/jquery.easy-pie-chart.js"></script>
    <script src="/WebAdminTheme/js/owl.carousel.js"></script>
    <script src="/WebAdminTheme/js/jquery.customSelect.min.js"></script>
    <script src="/WebAdminTheme/js/respond.min.js"></script>

    <script class="include" type="text/javascript" src="js/jquery.dcjqaccordion.2.7.js"></script>

    <!--common script for all pages-->
    <script src="/WebAdminTheme/js/common-scripts.js"></script>

    <!--script for this page-->
    <script src="/WebAdminTheme/js/sparkline-chart.js"></script>
    <script src="/WebAdminTheme/js/easy-pie-chart.js"></script>
    <script src="/WebAdminTheme/js/count.js"></script>

    <script>

        //owl carousel

        $(document).ready(function () {
            $("#owl-demo").owlCarousel({
                navigation: true,
                slideSpeed: 300,
                paginationSpeed: 400,
                singleItem: true,
                autoPlay: true

            });
        });

        //custom select box

        $(function () {
            $('select.styled').customSelect();
        });

    </script>

</body>
</html>